version: '2'

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev # For Firestore emulator usage when developing locally
      - GITHUB_URI=https://api.github.com/
      - GITHUB_TOKEN={ENTER GITHUB TOKEN}
      - PIPEDRIVE_URI={ENTER COMPANY PIPEDRIVE URI}
      - PIPEDRIVE_TOKEN={ENTER PIPEDRIVE API TOKEN}
      - PIPEDRIVE_PIPELINE_ID={ENTER PIPEDRIVE PIPELINE ID}
      - GIST_TOOL_APIKEY={ENTER A RANDOM VALUE TO USE AS AN APIKEY} # Any random String to authenticate requests
      - GOOGLE_CLOUD_PROJECT_ID={ENTER ANY PROJECT ID} #Must match FIRE_STORE_PROJECT_ID
      - LOCAL_FIRESTORE_HOST=firestore:8200

  firestore:
    image: mtlynch/firestore-emulator
    environment:
      - FIRESTORE_PROJECT_ID={ENTER ANY PROJECT ID} #Must match GOOGLE_CLOUD_PROJECT_ID
      - PORT=8200
    ports:
      - "8200:8200"
