version: '2'

services:
  app:
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - GITHUB_URI=https://api.github.com/
      - GITHUB_TOKEN={ENTER GITHUB TOKEN}
      - PIPEDRIVE_URI={ENTER COMPANY PIPEDRIVE URI}
      - PIPEDRIVE_TOKEN={ENTER PIPEDRIVE API TOKEN}
      - PIPEDRIVE_PIPELINE_ID={ENTER PIPEDRIVE PIPELINE ID}
      - GIST_TOOL_APIKEY={ENTER A RANDOM VALUE TO USE AS AN APIKEY}
      - GOOGLE_CLOUD_PROJECT_ID={ENTER GOOGLE CLOUD PROJECT ID}
      - GOOGLE_APPLICATION_CREDENTIALS=/root/.config/gcloud/{ENTER PRIVATE KEY FILENAME}
    volumes:
      - ~/.config/gcloud:/root/.config/gcloud