spring:
  application:
    name: gist-tool

logging:
  file:
    path: logs/
    name: logs/gist-tool.log

github:
  uri: ${GITHUB_URI}
  token: ${GITHUB_TOKEN}

pipedrive:
  uri: ${PIPEDRIVE_URI}
  token: ${PIPEDRIVE_TOKEN}
  pipeline:
    id: ${PIPEDRIVE_PIPELINE_ID}

gist:
  tool:
    apikey: ${GIST_TOOL_APIKEY}

google:
  cloud:
    projectId: ${GOOGLE_CLOUD_PROJECT_ID}
